apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ovsnodeosps.neutron.openstack.org
spec:
  group: neutron.openstack.org
  names:
    kind: OVSNodeOsp
    listKind: OVSNodeOspList
    plural: ovsnodeosps
    singular: ovsnodeosp
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: OVSNodeOsp is the Schema for the ovsnodeosps API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: OVSNodeOspSpec defines the desired state of OVSNodeOsp
            properties:
              nic:
                description: NIC for ovn encap ip
                type: string
              ovnSbRemote:
                description: ovn south db ip
                type: string
              ovsLogLevel:
                description: log level
                type: string
              ovsNodeOspImage:
                description: container image to run for the daemon
                type: string
              roleName:
                description: Name of the worker role created for OSP computes
                type: string
              serviceAccount:
                description: service account used to create pods
                type: string
            required:
            - nic
            - ovnSbRemote
            - ovsLogLevel
            - ovsNodeOspImage
            - roleName
            - serviceAccount
            type: object
          status:
            description: OVSNodeOspStatus defines the observed state of OVSNodeOsp
            properties:
              count:
                description: Count is the number of nodes the daemon is deployed to
                format: int32
                type: integer
              daemonsetHash:
                description: Daemonset hash used to detect changes
                type: string
            required:
            - count
            - daemonsetHash
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
